### PR TITLE
BUG: VR scene importing now behaving as expected

### LINKED ISSUE #75: VR view node not restored on scene load
Well, the value is saved, but the VR view node is not restored on scene reload.

### PR DESCRIPTION
**Pull request by adamrankin**
Fixes #75

* VR view node was not correctly detected on scene load, fixed
* VR widget UI was not correctly updated on new MRML data, fixed
* Changing of active VR node was not causing a UI update, fixed
* ActiveViewNode was not properly cleaned up on logic destruction, fixed

### CODE REVIEW

File: VirtualReality/qSlicerVirtualRealityModuleWidget.cxx [hunk 1]
```diff
@@ -125,23 +125,29 @@ void qSlicerVirtualRealityModuleWidget::updateWidgetFromMRML()
 
   wasBlocked = d->DesiredUpdateRateSlider->blockSignals(true);
   d->DesiredUpdateRateSlider->setValue(vrViewNode != NULL ? vrViewNode->GetDesiredUpdateRate() : 0);
+  this->onDesiredUpdateRateChanged(vrViewNode != NULL ? vrViewNode->GetDesiredUpdateRate() : 0);
```
Comment (cpinter) [inline VirtualReality/qSlicerVirtualRealityModuleWidget.cxx]: Could you please also change these "NULL"s to "nullptr"s? Once you're there :) Thanks

Comment (cpinter) [reply VirtualReality/qSlicerVirtualRealityModuleWidget.cxx]: I don't see the point in blocking signals and then calling the on... function manually. What's the reason for this?

Comment (adamrankin) [reply VirtualReality/qSlicerVirtualRealityModuleWidget.cxx]: No real reason. This way does everything in a single pass with no Qt event system triggered. Could do it the other way too. Same effect probably.

Comment (cpinter) [reply VirtualReality/qSlicerVirtualRealityModuleWidget.cxx]: Either you want the slot to be called or not. If you do, then you don't block the signal, or vice versa. The purpose of the updateWidgetFromMRML is to update the UI elements to reflect the MRML state. There should be no need to call the handler functions that serve the opposite purpose. So: what exactly is it that is needed to be done here, for which you added this call?

**Comment by cpinter** [comment]
Please amend the one commit instead of adding new ones. Thanks!

File: VirtualReality/qSlicerVirtualRealityModuleWidget.cxx (hunk 1 above)
Comment (adamrankin) [reply VirtualReality/qSlicerVirtualRealityModuleWidget.cxx]: The slot performs some logic to calculate the magnification value and then update an associated label. I want that to happen as right now the widget is not fully updated from the MRML data (the slider is, but the label is unchanged). Instead of copy-pasting the code, I called the slot as a function instead of a slot.

Comment (cpinter) [reply VirtualReality/qSlicerVirtualRealityModuleWidget.cxx]: In that case please separate this function out in its own function. There should be no MRML*->Set* call done from updateWidgetFromMRML

**Comment by cpinter** [comment]
Thanks @adamrankin looks good to me. If there are no further comments I'll integrate this soon
